"""Add user addresss m:M r/ship

Revision ID: 02d8a84c29d1
Revises: 7ed918dbff00
Create Date: 2020-12-01 15:05:02.347072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02d8a84c29d1'
down_revision = '7ed918dbff00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('user_address_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'address_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('user_address_id_fkey', 'user', 'address', ['address_id'], ['id'])
    op.drop_table('user_address')
    # ### end Alembic commands ###
