"""Add array field to tag table

Revision ID: 66f4132793c4
Revises: 8d25d1a86355
Create Date: 2020-12-16 11:07:20.303517

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '66f4132793c4'
down_revision = '8d25d1a86355'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('array', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'array')
    # ### end Alembic commands ###
