"""Add setter

Revision ID: 6876fcf3d658
Revises: fd52aa2728cb
Create Date: 2020-12-16 20:13:17.722760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6876fcf3d658'
down_revision = 'fd52aa2728cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', '_email')
    # ### end Alembic commands ###
