"""Add phone user 1:M r/ship

Revision ID: 7ed918dbff00
Revises: 07e93e5e1e4c
Create Date: 2020-12-01 14:30:46.289354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ed918dbff00'
down_revision = '07e93e5e1e4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'phone', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'phone', type_='foreignkey')
    op.drop_column('phone', 'user_id')
    # ### end Alembic commands ###
