"""add category model

Revision ID: 8d25d1a86355
Revises: 825a3074cac4
Create Date: 2020-12-15 17:57:23.683304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d25d1a86355'
down_revision = '825a3074cac4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_tree',
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('children_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['children_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category_tree')
    op.drop_table('category')
    # ### end Alembic commands ###
