"""empty message

Revision ID: d001efc3dd06
Revises: d6141985fa0a
Create Date: 2020-11-25 18:22:52.434501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd001efc3dd06'
down_revision = 'd6141985fa0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'address_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'address_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
