"""empty message

Revision ID: d6141985fa0a
Revises: a85a10cab360
Create Date: 2020-11-25 18:21:18.536008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6141985fa0a'
down_revision = 'a85a10cab360'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('user', sa.Column('address_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'address', ['address_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'address_id')
    op.drop_table('address')
    # ### end Alembic commands ###
