"""addd array field to tag table

Revision ID: d64b80bd7e62
Revises: e8991bbe3f8f
Create Date: 2020-12-16 11:24:44.693543

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd64b80bd7e62'
down_revision = 'e8991bbe3f8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('text_array', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'text_array')
    # ### end Alembic commands ###
