"""Add product model discount

Revision ID: fc1640e3929a
Revises: 71c6ca41f7b4
Create Date: 2020-12-16 15:32:45.060983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc1640e3929a'
down_revision = '71c6ca41f7b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('discount', sa.Numeric(precision=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'discount')
    # ### end Alembic commands ###
