"""Add product category

Revision ID: fd52aa2728cb
Revises: fc1640e3929a
Create Date: 2020-12-16 18:18:30.846450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd52aa2728cb'
down_revision = 'fc1640e3929a'
branch_labels = None
depends_on = None


def upgrade():
    # create_foreign_key, by default generates a None as 1st value, replacing it with suitable 
    # text makes sense
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key("category_product_id_fkey", 'product', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("category_product_id_fkey", 'product', type_='foreignkey')
    op.drop_column('product', 'category_id')
    # ### end Alembic commands ###
